# Generated by Django 5.0.3 on 2024-08-04 01:36

import problem.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProblemQuiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question",
                    models.ImageField(
                        blank=True, upload_to=problem.models.upload_filepath
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("option1", models.CharField(max_length=255)),
                ("option2", models.CharField(max_length=255)),
                ("option3", models.CharField(max_length=255)),
                ("option4", models.CharField(max_length=255)),
                ("correct_option", models.CharField(max_length=255)),
            ],
        ),
    ]
