name: Deploy (systemd-lite)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: SSH pull & restart via systemd
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -e
            cd ${{ secrets.PROJECT_DIR }}
            git pull origin main

            # (선택) 의존성 및 마이그레이션
            if [ -d "myvenv" ]; then
              source myvenv/bin/activate
              pip install --upgrade pip
              if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
              python manage.py migrate --noinput
            fi

            # 핵심: systemd로 재시작
            sudo systemctl restart uwsgi
            sudo nginx -t && sudo systemctl reload nginx || true
